server.port: 8761
spring:
  application:
    name: naming-server
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false